### ISSUE TITLE
md2pdf-client.py: config_path is correctly set on Windows

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [seanlano/md2pdf-client#6]
In md2pdf-client.py there is a TODO relating to Windows compatibility: `# TODO: Support Windows for this`. The code as-is will typically store the `.md2pdf.yaml` file in `C:\Users\<username>`, which is the equivalent to the Linux home directory sought. As such, I believe this TODO can be removed with no further feature implementation required (except maybe a comment adjustment to not specifically refer to Linux).

**Comment by seanlano** [comment]
Thanks, will-do.
